const shoeData = {
  shoe: [
    {
      brand: "Crocs",
      icon: "#crocs",
      viewBox: "'-5 0 522 380'",
      colorname: "blue-crocs",
      color: "#0061A0",
      price: 350,
      stock: {
        four: 3,
        six: 10,
      },
    },
    {
      brand: "Crocs",
      icon: "#crocs",
      viewBox: "'-5 -139 522 512'",
      colorname: "red-crocs",
      color: "#bf1131",
      price: 350,
      stock: {
        five: 8,
        seven: 5,
      },
    },
    {
      brand: "Converse",
      icon: "#converse",
      viewBox: "'-5 -112 522 512'",
      colorname: "green-converse",
      color: "#067335",
      price: 425,
      stock: {
        four: 2,
        five: 6,
      },
    },
    {
      brand: "Converse",
      icon: "#converse",
      viewBox: "'-5 -112 522 512'",
      colorname: "pink-converse",
      color: "#df677d",
      price: 425,
      stock: {
        five: 6,
        six: 12,
        eight: 2,
      },
    },
    {
      brand: "Vans",
      icon: "#vans",
      viewBox: "'-5 -154 522 512'",
      colorname: "black-vans",
      color: "#171717",
      price: 375,
      stock: {
        five: 2,
        six: 12,
        seven: 6,
      },
    },
    {
      brand: "Vans",
      icon: "#vans",
      viewBox: "'-5 -154 522 512'",
      colorname: "pink-vans",
      color: "#df677d",
      price: 375,
      stock: {
        five: 6,
      },
    },
    {
      brand: "Vans",
      icon: "#vans",
      viewBox: "'-5 -154 522 512'",
      colorname: "orange-vans",
      color: "#f28241",
      price: 375,
      stock: {
        four: 8,
      },
    },
    {
      brand: "Vans",
      icon: "#vans",
      viewBox: "'-5 -154 522 512'",
      colorname: "red-vans",
      color: "#bf1131",
      price: 375,
      stock: {
        six: 4,
      },
    },
    {
      brand: "Vans",
      icon: "#vans",
      viewBox: "'-5 -154 522 512'",
      colorname: "blue-vans",
      color: "#0061A0",
      price: 375,
      stock: {
        seven: 7,
      },
    },
    {
      brand: "Dr Martens",
      icon: "#dr-martens",
      viewBox: "'0 0 522 512'",
      colorname: "green-drmartens",
      color: "#067335",
      price: 600,
      stock: {
        eight: 3,
        nine: 1,
      },
    },
    {
      brand: "Dr Martens",
      icon: "#dr-martens",
      viewBox: "'0 0 522 512'",
      colorname: "pink-drmartens",
      color: "#df677d",
      price: 600,
      stock: {
        six: 4,
      },
    },
    {
      brand: "Dr Martens",
      icon: "#dr-martens",
      viewBox: "'0 0 522 512'",
      colorname: "orange-drmartens",
      color: "#f28241",
      price: 600,
      stock: {
        five: 6,
      },
    },
    {
      brand: "Dr Martens",
      icon: "#dr-martens",
      viewBox: "'0 0 522 512'",
      colorname: "blue-drmartens",
      color: "#0061A0",
      price: 600,
      stock: {
        six: 3,
      },
    },
    {
      brand: "Nike",
      icon: "#nike",
      viewBox: "'0 0 522 512'",
      colorname: "blue-nike",
      color: "#0061A0",
      price: 600,
      stock: {
        six: 3,
      },
    },
  ],
};

// const shoe_stock = [
//   {
//     brand: "Crocs",
//     color: "blue",
//     size: 4,
//     price: 350,
//     in_stock: 3,
//   },
//   {
//     brand: "Crocs",
//     color: "blue",
//     size: 6,
//     price: 350,
//     in_stock: 10,
//   },
//   {
//     brand: "Crocs",
//     color: "red",
//     size: 5,
//     price: 350,
//     in_stock: 8,
//   },
//   {
//     brand: "Crocs",
//     color: "red",
//     size: 7,
//     price: 350,
//     in_stock: 5,
//   },
//   {
//     brand: "Converse",
//     color: "green",
//     size: 4,
//     price: 425,
//     in_stock: 2,
//   },
//   {
//     brand: "Converse",
//     color: "green",
//     size: 5,
//     price: 425,
//     in_stock: 6,
//   },
//   {
//     brand: "Converse",
//     color: "green",
//     size: 6,
//     price: 425,
//     in_stock: 12,
//   },
//   {
//     brand: "Converse",
//     color: "purple",
//     size: 7,
//     price: 425,
//     in_stock: 5,
//   },
//   {
//     brand: "Converse",
//     color: "green",
//     size: 8,
//     price: 425,
//     in_stock: 2,
//   },
//   {
//     brand: "Converse",
//     color: "purple",
//     size: 6,
//     price: 425,
//     in_stock: 3,
//   },
//   {
//     brand: "Converse",
//     color: "purple",
//     size: 5,
//     price: 425,
//     in_stock: 1,
//   },
//   {
//     brand: "Vans",
//     color: "black",
//     size: 5,
//     price: 375,
//     in_stock: 2,
//   },
//   {
//     brand: "Vans",
//     color: "black",
//     size: 6,
//     price: 375,
//     in_stock: 12,
//   },
//   {
//     brand: "Vans",
//     color: "black",
//     size: 7,
//     price: 375,
//     in_stock: 6,
//   },
//   {
//     brand: "Vans",
//     color: "black",
//     size: 8,
//     price: 375,
//     in_stock: 3,
//   },
//   {
//     brand: "Vans",
//     color: "pink",
//     size: 5,
//     price: 375,
//     in_stock: 6,
//   },
//   {
//     brand: "Vans",
//     color: "orange",
//     size: 4,
//     price: 375,
//     in_stock: 8,
//   },
//   {
//     brand: "Vans",
//     color: "red",
//     size: 6,
//     price: 375,
//     in_stock: 4,
//   },
//   {
//     brand: "Vans",
//     color: "blue",
//     size: 7,
//     price: 375,
//     in_stock: 7,
//   },
//   {
//     brand: "Dr Martens",
//     color: "green",
//     size: 8,
//     price: 600,
//     in_stock: 3,
//   },
//   {
//     brand: "Dr Martens",
//     color: "green",
//     size: 8,
//     price: 600,
//     in_stock: 3,
//   },
//   {
//     brand: "Dr Martens",
//     color: "pink",
//     size: 6,
//     price: 600,
//     in_stock: 4,
//   },
//   {
//     brand: "Dr Martens",
//     color: "green",
//     size: 7,
//     price: 600,
//     in_stock: 1,
//   },
//   {
//     brand: "Dr Martens",
//     color: "orange",
//     size: 5,
//     price: 600,
//     in_stock: 6,
//   },
//   {
//     brand: "Dr Martens",
//     color: "blue",
//     size: 6,
//     price: 600,
//     in_stock: 3,
//   },
// ];

//[light shade, mid shade, dark shade]
const shoe_colors = {
  black: ["#212121", "#171717", "#000000"],
  blue: ["#0069B1", "#0061A0", "#00558C"],
  green: ["#038c3e", "#067335", "#05592a"],
  orange: ["#f2a03d", "#f28241", "#db693b"],
  pink: ["#df677d", "#d92344", "#a61b34"],
  purple: ["#9381d4", "#8575bf", "#7365a6"],
  red: ["#ca4f65", "#bf1131", "#8c0d24"],
};

const viewBox = {
  drmartens: "0 0 522 512",
  vans: "-5 -154 522 512",
  crocs: "-5 -139 522 512",
  converse: "-5 -112 522 512",
  nike: "-5 -117 522 512",
};
