const shoe_stock = [
  {
    brand: "Crocs",
    color: "blue",
    size: 4,
    price: 350,
    in_stock: 3,
  },
  {
    brand: "Crocs",
    color: "blue",
    size: 6,
    price: 350,
    in_stock: 10,
  },
  {
    brand: "Crocs",
    color: "red",
    size: 5,
    price: 350,
    in_stock: 8,
  },
  {
    brand: "Crocs",
    color: "red",
    size: 7,
    price: 350,
    in_stock: 5,
  },
  {
    brand: "Converse",
    color: "green",
    size: 4,
    price: 425,
    in_stock: 2,
  },
  {
    brand: "Converse",
    color: "green",
    size: 5,
    price: 425,
    in_stock: 6,
  },
  {
    brand: "Converse",
    color: "green",
    size: 6,
    price: 425,
    in_stock: 12,
  },
  {
    brand: "Converse",
    color: "purple",
    size: 7,
    price: 425,
    in_stock: 5,
  },
  {
    brand: "Converse",
    color: "green",
    size: 8,
    price: 425,
    in_stock: 2,
  },
  {
    brand: "Converse",
    color: "purple",
    size: 6,
    price: 425,
    in_stock: 3,
  },
  {
    brand: "Converse",
    color: "purple",
    size: 5,
    price: 425,
    in_stock: 1,
  },
  {
    brand: "Vans",
    color: "black",
    size: 5,
    price: 375,
    in_stock: 2,
  },
  {
    brand: "Vans",
    color: "black",
    size: 6,
    price: 375,
    in_stock: 12,
  },
  {
    brand: "Vans",
    color: "black",
    size: 7,
    price: 375,
    in_stock: 6,
  },
  {
    brand: "Vans",
    color: "black",
    size: 8,
    price: 375,
    in_stock: 3,
  },
  {
    brand: "Vans",
    color: "pink",
    size: 5,
    price: 375,
    in_stock: 6,
  },
  {
    brand: "Vans",
    color: "orange",
    size: 4,
    price: 375,
    in_stock: 8,
  },
  {
    brand: "Vans",
    color: "red",
    size: 6,
    price: 375,
    in_stock: 4,
  },
  {
    brand: "Vans",
    color: "blue",
    size: 7,
    price: 375,
    in_stock: 7,
  },
  {
    brand: "Dr Martens",
    color: "green",
    size: 8,
    price: 600,
    in_stock: 3,
  },
  {
    brand: "Dr Martens",
    color: "green",
    size: 8,
    price: 600,
    in_stock: 3,
  },
  {
    brand: "Dr Martens",
    color: "pink",
    size: 6,
    price: 600,
    in_stock: 4,
  },
  {
    brand: "Dr Martens",
    color: "green",
    size: 7,
    price: 600,
    in_stock: 1,
  },
  {
    brand: "Dr Martens",
    color: "orange",
    size: 5,
    price: 600,
    in_stock: 6,
  },
  {
    brand: "Dr Martens",
    color: "blue",
    size: 6,
    price: 600,
    in_stock: 3,
  },
];

//[light shade, mid shade, dark shade]
const shoe_colors = {
  black: ["#212121", "#171717", "#000000"],
  blue: ["#0069B1", "#0061A0", "#00558C"],
  green: ["#038c3e", "#067335", "#05592a"],
  orange: ["#f2a03d", "#f28241", "#db693b"],
  pink: ["#df677d", "#d92344", "#a61b34"],
  purple: ["#9381d4", "#8575bf", "#7365a6"],
  red: ["#ca4f65", "#bf1131", "#8c0d24"],
};
